# Generated by Django 5.2.3 on 2026-02-06 13:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("categories", "0001_initial"),
        ("products", "0002_remove_product_created_at_remove_product_updated_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="category",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="products",
                to="categories.category",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="slug",
            field=models.SlugField(default=""),
        ),
    ]
